version: '3.8'

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - APP_TEST_MODE=${APP_TEST_MODE}
      - APP_MAILING_PERIOD=${APP_MAILING_PERIOD}

      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}

      - OXR_BASE_URL=${OXR_BASE_URL}
      - OXR_APP_ID=${OXR_APP_ID}

      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - '${POSTGRESQL_PORT}:${POSTGRESQL_PORT}'
    command: -p ${POSTGRESQL_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
